Return-Path: <selinux-owner@vger.kernel.org>
X-Original-To: lists+selinux@lfdr.de
Delivered-To: lists+selinux@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id C6D6524B5F3
	for <lists+selinux@lfdr.de>; Thu, 20 Aug 2020 12:30:08 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1731433AbgHTKaE (ORCPT <rfc822;lists+selinux@lfdr.de>);
        Thu, 20 Aug 2020 06:30:04 -0400
Received: from mail3-relais-sop.national.inria.fr ([192.134.164.104]:34649
        "EHLO mail3-relais-sop.national.inria.fr" rhost-flags-OK-OK-OK-OK)
        by vger.kernel.org with ESMTP id S1731506AbgHTKU4 (ORCPT
        <rfc822;selinux@vger.kernel.org>); Thu, 20 Aug 2020 06:20:56 -0400
X-IronPort-AV: E=Sophos;i="5.76,332,1592863200"; 
   d="scan'208";a="356907302"
Received: from abo-173-121-68.mrs.modulonet.fr (HELO hadrien) ([85.68.121.173])
  by mail3-relais-sop.national.inria.fr with ESMTP/TLS/DHE-RSA-AES256-GCM-SHA384; 20 Aug 2020 12:20:51 +0200
Date:   Thu, 20 Aug 2020 12:20:51 +0200 (CEST)
From:   Julia Lawall <julia.lawall@inria.fr>
X-X-Sender: jll@hadrien
To:     Stephen Smalley <stephen.smalley.work@gmail.com>
cc:     kbuild-all@lists.01.org, selinux@vger.kernel.org,
        Paul Moore <paul@paul-moore.com>,
        Eric Paris <eparis@parisplace.org>,
        Ondrej Mosnacek <omosnace@redhat.com>,
        Tom Rix <trix@redhat.com>,
        Ethan Edwards <ethancarteredwards@gmail.com>,
        Wei Yongjun <weiyongjun1@huawei.com>, selinux@vger.kernel.org,
        linux-kernel@vger.kernel.org
Subject: [PATCH] selinux: fix memdup.cocci warnings
Message-ID: <alpine.DEB.2.22.394.2008201218350.2524@hadrien>
User-Agent: Alpine 2.22 (DEB 394 2020-01-19)
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Sender: selinux-owner@vger.kernel.org
Precedence: bulk
List-ID: <selinux.vger.kernel.org>
X-Mailing-List: selinux@vger.kernel.org

From: kernel test robot <lkp@intel.com>

Use kmemdup rather than duplicating its implementation

Generated by: scripts/coccinelle/api/memdup.cocci

Fixes: c7c556f1e81b ("selinux: refactor changing booleans")
CC: Stephen Smalley <stephen.smalley.work@gmail.com>
Signed-off-by: kernel test robot <lkp@intel.com>
Signed-off-by: Julia Lawall <julia.lawall@inria.fr>

---

tree:   https://git.kernel.org/pub/scm/linux/kernel/git/pcmoore/selinux.git next
head:   37ea433c66070fcef09c6d118492c36299eb72ba
commit: c7c556f1e81bb9e09656ed6650d0c44c84b7c016 [4/6] selinux: refactor changing booleans
:::::: branch date: 4 hours ago
:::::: commit date: 2 days ago

 conditional.c |    5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

--- a/security/selinux/ss/conditional.c
+++ b/security/selinux/ss/conditional.c
@@ -686,12 +686,11 @@ static int cond_bools_copy(struct hashta
 {
 	struct cond_bool_datum *datum;

-	datum = kmalloc(sizeof(struct cond_bool_datum), GFP_KERNEL);
+	datum = kmemdup(orig->datum, sizeof(struct cond_bool_datum),
+			GFP_KERNEL);
 	if (!datum)
 		return -ENOMEM;

-	memcpy(datum, orig->datum, sizeof(struct cond_bool_datum));
-
 	new->key = orig->key; /* No need to copy, never modified */
 	new->datum = datum;
 	return 0;
